Repository oss-review-toolkit/orthw, pull requests merged in 2022-07, with the labels that each got.

#11 orthw: Remove jq from required commands
  orthw
Labels: bug

#12 orthw: Add `check-advisories` command
  orthw
  orthwconfig-template
Labels: enhancement

#25 docs: Improve grammar, flow and consistency
  README.md
  docs/getting-started.md
Labels: documentation
